import { useState } from 'react';
import { NavLink, Outlet } from 'react-router-dom';
import { BarChart3, Bell, CalendarDays, CarFront, ClipboardCheck, FileText, Fuel, Home, LayoutDashboard, Menu, PlusCircle, ReceiptText, ShieldCheck, Wrench, X } from 'lucide-react';
import { isMockMode } from '../services/api.js';
import { useAppContext } from '../context/AppContext.jsx';

const navItems=[{to:'/',label:'Início',icon:Home,end:true},{to:'/reservas/nova',label:'Nova reserva',icon:PlusCircle},{to:'/reservas',label:'Minhas reservas',icon:CalendarDays},{to:'/operacao',label:'Retirada / devolução',icon:ClipboardCheck},{to:'/agenda',label:'Agenda da frota',icon:CarFront},{to:'/politica',label:'Política de uso',icon:ShieldCheck}];
const adminItems=[{to:'/admin',label:'Operação',icon:LayoutDashboard},{to:'/gestao',label:'Gestão executiva',icon:BarChart3},{to:'/gestao/centros-custo',label:'Centros de custo',icon:ReceiptText},{to:'/gestao/abastecimentos',label:'Abastecimentos',icon:Fuel},{to:'/gestao/manutencoes',label:'Manutenção',icon:Wrench},{to:'/gestao/documentos',label:'Documentos',icon:FileText},{to:'/gestao/multas',label:'Multas',icon:ReceiptText}];
export function AppShell(){const[open,setOpen]=useState(false);const{user,branding,loading,error}=useAppContext();const roles=user?.roles||[];const permissions=user?.permissions||[];const isAdmin=permissions.includes('*')||roles.some((r)=>['ADMIN','FROTA'].includes(r));const initials=(user?.name||'FL').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return <div className="app-shell">{open&&<button className="sidebar-backdrop" aria-label="Fechar menu" onClick={()=>setOpen(false)}/>}<aside className={`sidebar ${open?'is-open':''}`}><div className="brand-row"><div className="brand-mark">FL</div><div><strong>{branding?.productName||'Frota Leve'}</strong><span>Plataforma corporativa</span></div><button className="icon-button mobile-only" aria-label="Fechar menu" onClick={()=>setOpen(false)}><X size={20}/></button></div><nav className="sidebar-nav" aria-label="Navegação principal"><span className="nav-section-label">Operação</span>{navItems.map(({to,label,icon:Icon,end})=><NavLink key={to} to={to} end={end} onClick={()=>setOpen(false)} className={({isActive})=>`nav-link ${isActive?'active':''}`}><Icon size={19}/><span>{label}</span></NavLink>)}{isAdmin&&<><span className="nav-section-label admin-label">Administração</span>{adminItems.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/gestao'} onClick={()=>setOpen(false)} className={({isActive})=>`nav-link ${isActive?'active':''}`}><Icon size={19}/><span>{label}</span></NavLink>)}</>}</nav><div className="sidebar-footer">Versão 0.4 · Produto SaaS</div></aside><div className="app-column"><header className="topbar"><button className="icon-button mobile-only" aria-label="Abrir menu" onClick={()=>setOpen(true)}><Menu size={22}/></button><div className="topbar-spacer"/>{isMockMode&&<span className="prototype-pill">Dados de demonstração</span>}<button className="icon-button" aria-label="Notificações"><Bell size={20}/></button><div className="user-chip"><div className="avatar">{initials}</div><div><strong>{loading?'Carregando...':(user?.name||'Usuário')}</strong><span>{error?'Contexto indisponível':(user?.unit?.name||user?.unit||'')}</span></div></div></header><main className="main-content"><Outlet/></main></div></div>}
