import { pool } from '../config/db.js';import { ApiError } from '../utils/ApiError.js';import * as repo from '../repositories/managementCrud.repository.js';import { insertAudit } from '../repositories/audit.repository.js';import { optionalPositiveId,optionalString,requireDate,requireEnum,requireNumber,requireString } from '../utils/validate.js';
const fuelTypes=['GASOLINA','ETANOL','DIESEL','GNV','ELETRICO','OUTRO'];const fineStatuses=['PENDENTE','EM_TRATAMENTO','RECURSO','PAGA','CANCELADA'];
async function transaction(work){const c=await pool.getConnection();try{await c.beginTransaction();const r=await work(c);await c.commit();return r}catch(e){await c.rollback();throw e}finally{c.release()}}
function affectedOr404(n){if(!n)throw new ApiError(404,'RECURSO_NAO_ENCONTRADO','Registro não encontrado.')}async function sameTenant(c,empresaId,refs){for(const[table,id]of refs){if(id==null)continue;if(!await repo.existsTenantResource(c,table,empresaId,id))throw new ApiError(400,'REFERENCIA_INVALIDA','Um recurso relacionado não pertence à empresa atual ou não existe.')}}
const audit=(c,ctx,action,entity,id,after,before=null)=>insertAudit(c,{empresaId:ctx.empresaId,userId:ctx.userId,action,entity,entityId:id,before,after,requestId:ctx.requestId,ip:ctx.ip,userAgent:ctx.userAgent});
export const managementCrudService={
 listCostCenters:(empresaId,q)=>repo.listCostCenters(empresaId,{q:String(q.q||'').trim()}),
 createCostCenter(ctx,body){const data={codigo:requireString(body.codigo,'codigo',{min:1,max:50}).toUpperCase(),nome:requireString(body.nome,'nome',{min:2,max:120}),descricao:optionalString(body.descricao,'descricao',{max:255})};return transaction(async c=>{const id=await repo.insertCostCenter(c,ctx.empresaId,data);await audit(c,ctx,'CENTRO_CUSTO_CRIADO','CENTRO_CUSTO',id,data);return{id}})},
 updateCostCenter(ctx,id,body){const data={codigo:requireString(body.codigo,'codigo',{min:1,max:50}).toUpperCase(),nome:requireString(body.nome,'nome',{min:2,max:120}),descricao:optionalString(body.descricao,'descricao',{max:255})};return transaction(async c=>{affectedOr404(await repo.updateCostCenter(c,ctx.empresaId,id,data));await audit(c,ctx,'CENTRO_CUSTO_EDITADO','CENTRO_CUSTO',id,data);return{id}})},
 setCostCenterActive(ctx,id,active){return transaction(async c=>{affectedOr404(await repo.setCostCenterActive(c,ctx.empresaId,id,active));await audit(c,ctx,'CENTRO_CUSTO_STATUS','CENTRO_CUSTO',id,{ativo:active});return{id,ativo:active}})},
 listFuelings:(empresaId,q)=>repo.listFuelings(empresaId,{q:String(q.q||'').trim()}),
 createFueling(ctx,body){const data={veiculoId:Number(body.veiculoId),motoristaId:optionalPositiveId(body.motoristaId,'motoristaId'),operacaoId:optionalPositiveId(body.operacaoId,'operacaoId'),centroCustoId:optionalPositiveId(body.centroCustoId,'centroCustoId'),dataHora:requireDate(body.dataHora,'dataHora'),quilometragem:requireNumber(body.quilometragem,'quilometragem',{min:0}),tipoCombustivel:requireEnum(body.tipoCombustivel,'tipoCombustivel',fuelTypes),litros:requireNumber(body.litros,'litros',{min:.001}),valorTotal:requireNumber(body.valorTotal,'valorTotal',{min:0}),posto:optionalString(body.posto,'posto',{max:180}),comprovanteUrl:optionalString(body.comprovanteUrl,'comprovanteUrl',{max:500}),observacao:optionalString(body.observacao,'observacao',{max:500})};if(!Number.isInteger(data.veiculoId)||data.veiculoId<=0)throw new ApiError(400,'VALIDACAO','veiculoId inválido.');return transaction(async c=>{await sameTenant(c,ctx.empresaId,[['veiculos',data.veiculoId],['usuarios',data.motoristaId],['operacoes_veiculo',data.operacaoId],['centros_custo',data.centroCustoId]]);const id=await repo.insertFueling(c,ctx.empresaId,ctx.userId,data);await audit(c,ctx,'ABASTECIMENTO_CRIADO','ABASTECIMENTO',id,data);return{id}})},
 cancelFueling(ctx,id,body){const motivo=requireString(body.motivo,'motivo',{min:3,max:500});return transaction(async c=>{affectedOr404(await repo.cancelFueling(c,ctx.empresaId,id,ctx.userId,motivo));await audit(c,ctx,'ABASTECIMENTO_CANCELADO','ABASTECIMENTO',id,{motivo});return{id,status:'CANCELADO'}})},
 listMaintenancePlans:(empresaId,q)=>repo.listMaintenancePlans(empresaId,{q:String(q.q||'').trim()}),
 createMaintenancePlan(ctx,body){const data=normalizeMaintenance(body);return transaction(async c=>{await sameTenant(c,ctx.empresaId,[['veiculos',data.veiculoId]]);const id=await repo.insertMaintenancePlan(c,ctx.empresaId,data);await audit(c,ctx,'PLANO_MANUTENCAO_CRIADO','PLANO_MANUTENCAO',id,data);return{id}})},
 updateMaintenancePlan(ctx,id,body){const data=normalizeMaintenance(body);return transaction(async c=>{await sameTenant(c,ctx.empresaId,[['veiculos',data.veiculoId]]);affectedOr404(await repo.updateMaintenancePlan(c,ctx.empresaId,id,data));await audit(c,ctx,'PLANO_MANUTENCAO_EDITADO','PLANO_MANUTENCAO',id,data);return{id}})},
 setMaintenancePlanActive(ctx,id,active){return transaction(async c=>{affectedOr404(await repo.setMaintenancePlanActive(c,ctx.empresaId,id,active));await audit(c,ctx,'PLANO_MANUTENCAO_STATUS','PLANO_MANUTENCAO',id,{ativo:active});return{id,ativo:active}})},
 listDocuments(empresaId,q){const type=String(q.tipo||'VEICULO').toUpperCase();if(!['VEICULO','USUARIO'].includes(type))throw new ApiError(400,'VALIDACAO','tipo deve ser VEICULO ou USUARIO.');return repo.listDocuments(empresaId,type)},
 createDocument(ctx,body){const type=requireEnum(body.entidadeTipo,'entidadeTipo',['VEICULO','USUARIO']);const data={ownerId:Number(body.entidadeId),tipo:requireString(body.tipo,'tipo',{min:2,max:50}),numero:optionalString(body.numero,'numero',{max:100}),categoria:optionalString(body.categoria,'categoria',{max:50}),emissaoEm:body.emissaoEm||null,validadeEm:body.validadeEm||null,alertaDias:body.alertaDias==null?30:requireNumber(body.alertaDias,'alertaDias',{min:0,max:3650}),arquivoUrl:optionalString(body.arquivoUrl,'arquivoUrl',{max:500}),observacao:optionalString(body.observacao,'observacao',{max:500})};if(!Number.isInteger(data.ownerId)||data.ownerId<=0)throw new ApiError(400,'VALIDACAO','entidadeId inválido.');return transaction(async c=>{await sameTenant(c,ctx.empresaId,[[type==='USUARIO'?'usuarios':'veiculos',data.ownerId]]);const id=await repo.insertDocument(c,ctx.empresaId,ctx.userId,type,data);await audit(c,ctx,'DOCUMENTO_CRIADO',`DOCUMENTO_${type}`,id,data);return{id,entidadeTipo:type}})},
 cancelDocument(ctx,id,body){const type=requireEnum(body.entidadeTipo,'entidadeTipo',['VEICULO','USUARIO']);return transaction(async c=>{affectedOr404(await repo.cancelDocument(c,ctx.empresaId,id,type));await audit(c,ctx,'DOCUMENTO_CANCELADO',`DOCUMENTO_${type}`,id,{status:'CANCELADO'});return{id,status:'CANCELADO'}})},
 listFines(empresaId,q){const status=q.status?requireEnum(q.status,'status',fineStatuses):null;return repo.listFines(empresaId,{status})},
 createFine(ctx,body){const data={veiculoId:Number(body.veiculoId),motoristaId:optionalPositiveId(body.motoristaId,'motoristaId'),reservaId:optionalPositiveId(body.reservaId,'reservaId'),operacaoId:optionalPositiveId(body.operacaoId,'operacaoId'),centroCustoId:optionalPositiveId(body.centroCustoId,'centroCustoId'),autoInfracao:optionalString(body.autoInfracao,'autoInfracao',{max:100}),dataHoraInfracao:requireDate(body.dataHoraInfracao,'dataHoraInfracao'),descricao:requireString(body.descricao,'descricao',{min:3,max:500}),localInfracao:optionalString(body.localInfracao,'localInfracao',{max:255}),valor:requireNumber(body.valor,'valor',{min:0}),pontos:body.pontos==null?null:requireNumber(body.pontos,'pontos',{min:0,max:20}),vencimentoEm:body.vencimentoEm||null,documentoUrl:optionalString(body.documentoUrl,'documentoUrl',{max:500}),observacao:optionalString(body.observacao,'observacao',{max:500})};if(!Number.isInteger(data.veiculoId)||data.veiculoId<=0)throw new ApiError(400,'VALIDACAO','veiculoId inválido.');return transaction(async c=>{await sameTenant(c,ctx.empresaId,[['veiculos',data.veiculoId],['usuarios',data.motoristaId],['reservas',data.reservaId],['operacoes_veiculo',data.operacaoId],['centros_custo',data.centroCustoId]]);const id=await repo.insertFine(c,ctx.empresaId,ctx.userId,data);await audit(c,ctx,'MULTA_CRIADA','MULTA',id,data);return{id}})},
 updateFineStatus(ctx,id,body){const status=requireEnum(body.status,'status',fineStatuses),pagoEm=status==='PAGA'?(body.pagoEm||new Date().toISOString().slice(0,10)):null;return transaction(async c=>{affectedOr404(await repo.updateFineStatus(c,ctx.empresaId,id,status,pagoEm));await audit(c,ctx,'MULTA_STATUS','MULTA',id,{status,pagoEm});return{id,status}})}
};
function normalizeMaintenance(body){const intervaloKm=body.intervaloKm==null||body.intervaloKm===''?null:requireNumber(body.intervaloKm,'intervaloKm',{min:1});const intervaloDias=body.intervaloDias==null||body.intervaloDias===''?null:requireNumber(body.intervaloDias,'intervaloDias',{min:1});if(!intervaloKm&&!intervaloDias)throw new ApiError(400,'VALIDACAO','Informe intervaloKm ou intervaloDias.');const veiculoId=Number(body.veiculoId);if(!Number.isInteger(veiculoId)||veiculoId<=0)throw new ApiError(400,'VALIDACAO','veiculoId inválido.');return{veiculoId,nome:requireString(body.nome,'nome',{min:2,max:120}),descricao:optionalString(body.descricao,'descricao',{max:500}),intervaloKm,intervaloDias,ultimoKm:body.ultimoKm==null||body.ultimoKm===''?null:requireNumber(body.ultimoKm,'ultimoKm',{min:0}),ultimaData:body.ultimaData||null,proximoKm:body.proximoKm==null||body.proximoKm===''?null:requireNumber(body.proximoKm,'proximoKm',{min:0}),proximaData:body.proximaData||null,antecedenciaAlertaKm:body.antecedenciaAlertaKm==null?1000:requireNumber(body.antecedenciaAlertaKm,'antecedenciaAlertaKm',{min:0}),antecedenciaAlertaDias:body.antecedenciaAlertaDias==null?30:requireNumber(body.antecedenciaAlertaDias,'antecedenciaAlertaDias',{min:0})}}
