import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarClock, Check, MapPin, Plus, Trash2, UserRound } from 'lucide-react';
import { VehicleCard } from '../components/VehicleCard.jsx';
import { createReservation, getAvailableVehicles, getCities, getCostCentersForReservation, getDrivers, getStates, zonedLocalInstant } from '../services/api.js';
import { useAppContext } from '../context/AppContext.jsx';

const steps=['Período','Veículo','Viagem','Confirmar'];
const today=()=>new Date().toISOString().slice(0,10);
const emptyDestination=(stateId='')=>({stateId:String(stateId||''),cityCode:''});
export function NewReservationPage(){
 const{user,settings}=useAppContext();const[step,setStep]=useState(0);const[period,setPeriod]=useState({startDate:today(),startTime:'08:30',endDate:today(),endTime:'12:00'});const[vehicles,setVehicles]=useState([]),[selectedVehicle,setSelectedVehicle]=useState(null);const[drivers,setDrivers]=useState([]),[centers,setCenters]=useState([]),[states,setStates]=useState([]),[citiesByState,setCitiesByState]=useState({});const[driverId,setDriverId]=useState(''),[centerId,setCenterId]=useState(''),[destinations,setDestinations]=useState([emptyDestination()]);const[reason,setReason]=useState(''),[ticket,setTicket]=useState(''),[notes,setNotes]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[createdId,setCreatedId]=useState(null);
 useEffect(()=>{Promise.all([getDrivers(),getCostCentersForReservation(),getStates()]).then(([d,c,s])=>{setDrivers(d);setCenters(c);setStates(s);setDriverId(String(user?.id||d[0]?.id||''));setCenterId(String(c[0]?.id||''));if(s[0]){setDestinations([emptyDestination(s[0].id)]);loadCities(s[0].id)}}).catch(e=>setError(e.message))},[user?.id]);
 async function loadCities(stateId){if(!stateId||citiesByState[stateId])return;try{const data=await getCities(stateId);setCitiesByState(v=>({...v,[stateId]:data}))}catch(e){setError(e.message)}}
 const selectedDriver=drivers.find(x=>String(x.id)===driverId);const destinationLabels=useMemo(()=>destinations.map(item=>{const state=states.find(s=>String(s.id)===item.stateId);const city=(citiesByState[item.stateId]||[]).find(c=>String(c.ibgeCode)===item.cityCode);return city&&state?`${city.name} - ${state.uf}`:'Destino não informado'}),[destinations,states,citiesByState]);
 function instants(){return{start:zonedLocalInstant(period.startDate,period.startTime,settings?.timezone),end:zonedLocalInstant(period.endDate,period.endTime,settings?.timezone)}}
 async function searchVehicles(){setError('');try{const{iStart,iEnd}={iStart:new Date(instants().start),iEnd:new Date(instants().end)};if(iEnd<=iStart){setError('O retorno deve ser posterior à saída.');return}setLoading(true);const data=await getAvailableVehicles({...period,timeZone:settings?.timezone});setVehicles(data);setSelectedVehicle(null);setStep(1)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function updateDestination(index,field,value){setDestinations(cur=>cur.map((item,i)=>i===index?{...item,[field]:value,...(field==='stateId'?{cityCode:''}:{})}:item));if(field==='stateId')await loadCities(value)}
 function validateTrip(){if(!driverId){setError('Selecione o motorista.');return false}if(settings?.requireCostCenter&&!centerId){setError('Selecione o centro de custo.');return false}if(destinations.some(d=>!d.stateId||!d.cityCode)){setError('Selecione Estado e Cidade em todos os destinos.');return false}if(reason.trim().length<5){setError('Informe o motivo com pelo menos 5 caracteres.');return false}if(settings?.requireTicket&&!ticket.trim()){setError('O número do chamado é obrigatório para esta empresa.');return false}setError('');return true}
 async function confirm(){try{setLoading(true);setError('');const times=instants();const result=await createReservation({veiculoId:selectedVehicle.id,motoristaId:Number(driverId),centroCustoId:centerId?Number(centerId):null,dataHoraInicio:times.start,dataHoraFim:times.end,motivo:reason.trim(),numeroChamado:ticket.trim()||null,observacao:notes.trim()||null,destinos:destinations.map(d=>({codigoIbge:Number(d.cityCode)}))});setCreatedId(result.id)}catch(e){setError(e.message)}finally{setLoading(false)}}
 if(createdId)return <div className="success-screen"><div className="success-icon"><Check size={30}/></div><span className="eyebrow">Reserva #{createdId}</span><h1>Reserva confirmada</h1><p>{selectedVehicle?.brand||selectedVehicle?.marca} {selectedVehicle?.model||selectedVehicle?.modelo}</p><div className="success-actions"><a className="button primary" href="/reservas">Ver minhas reservas</a><a className="button secondary" href="/reservas/nova">Fazer outra reserva</a></div></div>;
 return <div className="page-stack narrow-page"><div className="page-heading"><span className="eyebrow">Reserva de veículo</span><h1>Nova reserva</h1><p>Períodos podem atravessar dias; horários seguem o timezone {settings?.timezone||'da empresa'}.</p></div><ol className="stepper">{steps.map((label,index)=><li key={label} className={`${index===step?'current':''} ${index<step?'done':''}`}><span>{index<step?<Check size={16}/>:index+1}</span><b>{label}</b></li>)}</ol>{error&&<div className="alert error" role="alert">{error}</div>}
 {step===0&&<section className="form-card"><div className="form-card-title"><CalendarClock/><div><h2>Quando você precisa do veículo?</h2><p>Intervalo configurado: {settings?.reservationIntervalMinutes||30} minutos.</p></div></div><div className="form-grid two"><label>Data/hora de saída<div className="form-grid two"><input type="date" value={period.startDate} onChange={e=>setPeriod({...period,startDate:e.target.value})}/><input type="time" step={(settings?.reservationIntervalMinutes||30)*60} value={period.startTime} onChange={e=>setPeriod({...period,startTime:e.target.value})}/></div></label><label>Data/hora de retorno<div className="form-grid two"><input type="date" value={period.endDate} onChange={e=>setPeriod({...period,endDate:e.target.value})}/><input type="time" step={(settings?.reservationIntervalMinutes||30)*60} value={period.endTime} onChange={e=>setPeriod({...period,endTime:e.target.value})}/></div></label></div><div className="form-actions end"><button className="button primary" onClick={searchVehicles} disabled={loading}>{loading?'Buscando...':'Buscar veículos'} <ArrowRight size={18}/></button></div></section>}
 {step===1&&<section className="form-card"><div className="vehicle-grid">{vehicles.map(v=><VehicleCard key={v.id} vehicle={v} selected={selectedVehicle?.id===v.id} onSelect={setSelectedVehicle}/>)}</div>{!vehicles.length&&<div className="empty-state"><strong>Nenhum veículo disponível</strong></div>}<div className="form-actions between"><button className="button secondary" onClick={()=>setStep(0)}><ArrowLeft size={18}/> Alterar período</button><button className="button primary" disabled={!selectedVehicle} onClick={()=>setStep(2)}>Continuar <ArrowRight size={18}/></button></div></section>}
 {step===2&&<section className="form-card"><div className="form-card-title"><UserRound/><div><h2>Dados da viagem</h2><p>Solicitante: {user?.name||'Usuário atual'}</p></div></div><div className="form-grid two"><label>Motorista<select required value={driverId} onChange={e=>setDriverId(e.target.value)}>{drivers.map(d=><option key={d.id} value={d.id}>{d.name||d.nome} · {d.employeeCode||d.codigoFuncionario||''}</option>)}</select></label><label>Centro de custo {settings?.requireCostCenter?'*':'(opcional)'}<select value={centerId} onChange={e=>setCenterId(e.target.value)}><option value="">Selecione...</option>{centers.map(c=><option key={c.id} value={c.id}>{c.codigo||c.code} · {c.nome||c.name}</option>)}</select></label></div><div className="form-divider"/><div className="form-card-title compact-title"><MapPin/><div><h3>Destino(s)</h3><p>Máximo de {settings?.maxDestinations||10} cidades.</p></div></div><div className="destination-stack">{destinations.map((d,index)=><div className="destination-row" key={index}><div className="destination-index">{index+1}</div><label>Estado<select value={d.stateId} onChange={e=>updateDestination(index,'stateId',e.target.value)}><option value="">Selecione...</option>{states.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Cidade<select value={d.cityCode} onChange={e=>updateDestination(index,'cityCode',e.target.value)}><option value="">Selecione...</option>{(citiesByState[d.stateId]||[]).map(c=><option key={c.ibgeCode} value={c.ibgeCode}>{c.name}</option>)}</select></label>{index>0&&<button className="icon-button danger" onClick={()=>setDestinations(cur=>cur.filter((_,i)=>i!==index))}><Trash2 size={18}/></button>}</div>)}</div>{destinations.length<(settings?.maxDestinations||10)&&<button className="add-destination" type="button" onClick={()=>setDestinations(cur=>[...cur,emptyDestination(states[0]?.id)])}><Plus size={18}/> Adicionar destino</button>}<label>Motivo da viagem *<textarea rows="3" value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="form-grid two"><label>Nº do chamado {settings?.requireTicket?'*':'(opcional)'}<input value={ticket} onChange={e=>setTicket(e.target.value)}/></label><label>Observação (opcional)<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="form-actions between"><button className="button secondary" onClick={()=>setStep(1)}><ArrowLeft size={18}/> Voltar</button><button className="button primary" onClick={()=>validateTrip()&&setStep(3)}>Revisar <ArrowRight size={18}/></button></div></section>}
 {step===3&&<section className="form-card"><div className="form-card-title"><Check/><div><h2>Confirme sua reserva</h2><p>A disponibilidade será revalidada na transação.</p></div></div><div className="review-grid"><div className="review-item"><span>Veículo</span><strong>{selectedVehicle?.brand||selectedVehicle?.marca} {selectedVehicle?.model||selectedVehicle?.modelo}</strong></div><div className="review-item"><span>Período</span><strong>{period.startDate} {period.startTime}</strong><small>até {period.endDate} {period.endTime}</small></div><div className="review-item"><span>Motorista</span><strong>{selectedDriver?.name||selectedDriver?.nome}</strong></div><div className="review-item wide"><span>Destinos</span><strong>{destinationLabels.join(' → ')}</strong></div><div className="review-item wide"><span>Motivo</span><strong>{reason}</strong></div></div><div className="form-actions between"><button className="button secondary" onClick={()=>setStep(2)}><ArrowLeft size={18}/> Voltar</button><button className="button primary" disabled={loading} onClick={confirm}>{loading?'Confirmando...':'Confirmar reserva'} <Check size={18}/></button></div></section>}
 </div>}
